debug: true
server:
  port: 8081
practicum:
  kafka:
    consumer:
      enabled: true
      bootstrap-servers: localhost:9092
      group-id: 123
      topic: "my-topic"
      offset-reset: "earliest"
